<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <NoStandardLibraries>false</NoStandardLibraries>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Portable;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Portable|AnyCPU'">
    <OutputPath>bin\Portable\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Transactions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfoCommon.cs">
      <Link>Properties\AssemblyInfoCommon.cs</Link>
    </Compile>
    <Compile Include="..\AssemblyVersionCommon.cs">
      <Link>Properties\AssemblyVersionCommon.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AstroGrep.Common\AstroGrep.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="5.0.2" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="IFileFilterSpec.cs" />
    <Compile Remove="AssemblyInfo.cs" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio AllowExistingFolder="true" />
  </ProjectExtensions>
</Project>