<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Portable;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Portable|AnyCPU'">
    <OutputPath>bin\Portable\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyInfoCommon.cs">
      <Link>Properties\AssemblyInfoCommon.cs</Link>
    </Compile>
    <Compile Include="..\AssemblyVersionCommon.cs">
      <Link>Properties\AssemblyVersionCommon.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="5.0.2" />
  </ItemGroup>
</Project>